-- MySQL Script generated by MySQL Workbench
-- Sun Dec  3 18:09:31 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema movies-imdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `movies-imdb` ;

-- -----------------------------------------------------
-- Schema movies-imdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `movies-imdb` DEFAULT CHARACTER SET utf8 ;
USE `movies-imdb` ;

-- -----------------------------------------------------
-- Table `movies-imdb`.`title_basics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies-imdb`.`title_basics` ;

CREATE TABLE IF NOT EXISTS `movies-imdb`.`title_basics` (
  `tconst` INT NOT NULL,
  `primary_title` VARCHAR(45) NULL,
  `start_year` VARCHAR(45) NULL,
  `runtime` FLOAT NULL,
  PRIMARY KEY (`tconst`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies-imdb`.`raitngs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies-imdb`.`raitngs` ;

CREATE TABLE IF NOT EXISTS `movies-imdb`.`raitngs` (
  `tconstant` INT NOT NULL,
  `average_rating` VARCHAR(45) NULL,
  `number_of_votes` INT NULL,
  PRIMARY KEY (`tconstant`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies-imdb`.`genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies-imdb`.`genres` ;

CREATE TABLE IF NOT EXISTS `movies-imdb`.`genres` (
  `genre_id` INT NOT NULL,
  `title_genres` VARCHAR(45) NULL,
  PRIMARY KEY (`genre_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies-imdb`.`title_genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies-imdb`.`title_genres` ;

CREATE TABLE IF NOT EXISTS `movies-imdb`.`title_genres` (
  `tconstant` INT NOT NULL,
  `genre_id` INT NOT NULL,
  PRIMARY KEY (`tconstant`, `genre_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
